# Generated by cpp11: do not edit by hand

dtri_cpp <- function(x, min, max, mode, log) {
  .Call(`_triangulr_dtri_cpp`, x, min, max, mode, log)
}

dtri_cpp2 <- function(x, min, max, mode, log) {
  .Call(`_triangulr_dtri_cpp2`, x, min, max, mode, log)
}
