# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

QTriangC <- function(p, min, max, mode, lower_tail, log_p) {
    .Call('_triangulr_QTriangC', PACKAGE = 'triangulr', p, min, max, mode, lower_tail, log_p)
}

QTriangC2 <- function(p, min, max, mode, lower_tail, log_p) {
    .Call('_triangulr_QTriangC2', PACKAGE = 'triangulr', p, min, max, mode, lower_tail, log_p)
}

RTriangC <- function(n, min, max, mode) {
    .Call('_triangulr_RTriangC', PACKAGE = 'triangulr', n, min, max, mode)
}

RTriangC2 <- function(n, min, max, mode) {
    .Call('_triangulr_RTriangC2', PACKAGE = 'triangulr', n, min, max, mode)
}

