# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CTriC <- function(t, min, max, mode) {
    .Call('_triangulr_CTriC', PACKAGE = 'triangulr', t, min, max, mode)
}

CTriC2 <- function(t, min, max, mode) {
    .Call('_triangulr_CTriC2', PACKAGE = 'triangulr', t, min, max, mode)
}

DTriC <- function(x, min, max, mode, log) {
    .Call('_triangulr_DTriC', PACKAGE = 'triangulr', x, min, max, mode, log)
}

DTriC2 <- function(x, min, max, mode, log) {
    .Call('_triangulr_DTriC2', PACKAGE = 'triangulr', x, min, max, mode, log)
}

MTriC <- function(t, min, max, mode) {
    .Call('_triangulr_MTriC', PACKAGE = 'triangulr', t, min, max, mode)
}

MTriC2 <- function(t, min, max, mode) {
    .Call('_triangulr_MTriC2', PACKAGE = 'triangulr', t, min, max, mode)
}

PTriC <- function(x, min, max, mode, lower_tail, log_p) {
    .Call('_triangulr_PTriC', PACKAGE = 'triangulr', x, min, max, mode, lower_tail, log_p)
}

PTriC2 <- function(x, min, max, mode, lower_tail, log_p) {
    .Call('_triangulr_PTriC2', PACKAGE = 'triangulr', x, min, max, mode, lower_tail, log_p)
}

QTriC <- function(p, min, max, mode, lower_tail, log_p) {
    .Call('_triangulr_QTriC', PACKAGE = 'triangulr', p, min, max, mode, lower_tail, log_p)
}

QTriC2 <- function(p, min, max, mode, lower_tail, log_p) {
    .Call('_triangulr_QTriC2', PACKAGE = 'triangulr', p, min, max, mode, lower_tail, log_p)
}

RTriC <- function(n, min, max, mode) {
    .Call('_triangulr_RTriC', PACKAGE = 'triangulr', n, min, max, mode)
}

RTriC2 <- function(n, min, max, mode) {
    .Call('_triangulr_RTriC2', PACKAGE = 'triangulr', n, min, max, mode)
}

